import { Hono } from "hono";
import type { Env } from "./app";
import { blocks } from "./pages/blocks";
import { blockDetail } from "./pages/block-detail";
import { transactions } from "./pages/transactions";
import { txDetail } from "./pages/tx-detail";
import { accounts } from "./pages/accounts";
import { account } from "./pages/account";
import { market } from "./pages/market";
import { miners } from "./pages/miners";
import { minerDetail } from "./pages/miner-detail";
import { charts } from "./pages/charts";
import { assets } from "./pages/assets";
import { contracts } from "./pages/contracts";
import { search } from "./pages/assets";

export const pages = new Hono<{ Bindings: Env }>();

pages.route("/", blocks);
pages.route("/", blockDetail);
pages.route("/", transactions);
pages.route("/", txDetail);
pages.route("/", accounts);
pages.route("/", account);
pages.route("/", market);
pages.route("/", miners);
pages.route("/", minerDetail);
pages.route("/", charts);
pages.route("/", assets);
pages.route("/", contracts);
pages.route("/", search);
